name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: 192.168.43.128:30080
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: 192.168.43.128:30080/homelab/kubernetes-homelab-web:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Rollout restart on K3s
        run: kubectl rollout restart deployment/fastapi -n homelab
      - name: Wait for rollout to complete
        run: kubectl rollout status deployment/fastapi -n homelab --timeout=120s
